name: shell commands

on:
    - push

# env:
#     AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
#     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
    terraform-workflow:
        permissions:
            contents: write
            issues: write
            pull-requests: write

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Set Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.1.0
            - name: Terraform init
              run: terraform init
            - name: Terraform validate
              run: terraform validate
            - name: Terraform plan
              run: terraform plan
            - name: release
              run: npx semantic-release
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            # - name: Terraform apply
            #   run: terraform apply -auto-approve
            # - name: Terraform apply
            #   run: terraform apply
            - name: Terraform destroy
              run: terraform destroy -auto-approve
